feat: check tests1

diff --git a/deploy.jenkinsfile b/deploy.jenkinsfile
--- a/deploy.jenkinsfile
+++ b/deploy.jenkinsfile
@@ -97,10 +97,9 @@ pipeline {
                     sh "pkill -f 'port-forward svc/myapp-service' || true"
 
                     sh """
-                        export KUBECONFIG=${env.KUBECONFIG}
-                        echo "KUBECONFIG is: \$KUBECONFIG"
-                        kubectl get pods -n ${params.ENVIRONMENT}
-                        kubectl port-forward svc/myapp-service 8001:8000 \
+                        ls -la \${KUBECONFIG} || echo "KUBECONFIG FILE NOT FOUND"
+                        kubectl --kubeconfig=\${KUBECONFIG} get pods -n ${params.ENVIRONMENT}
+                        kubectl --kubeconfig=\${KUBECONFIG} port-forward svc/myapp-service 8001:8000 \
                             -n ${params.ENVIRONMENT} \
                             --address 127.0.0.1 > pf.log 2>&1 &
                         echo \$! > pf.pid
