feat: edit deployJenkinsfile

diff --git a/deploy.jenkinsfile b/deploy.jenkinsfile
--- a/deploy.jenkinsfile
+++ b/deploy.jenkinsfile
@@ -15,14 +15,23 @@ pipeline {
                     def isStaging = (params.ENVIRONMENT == 'staging')
                     def currentStage = isStaging ? 'Deploy to Staging' : 'Deploy to Production'
 
-                    conditionalStage(name: currentStage, condition: true) {
+                        conditionalStage(name: currentStage, condition: true) {
                         checkout scm
-                        withCredentials([file(credentialsId: 'ENV_FILE', variable: 'SECRET_FILE_PATH')]) {
-                            echo "Deploying Green Slot"
-                            sh """
-                                IMAGE_NAME=${params.IMAGE_TAG} APP_PORT=8001 \
-                                docker compose -p app-green --env-file "${SECRET_FILE_PATH}" up -d
-                            """
+
+                        withCredentials([
+                            file(credentialsId: 'ENV_FILE', variable: 'SECRET_FILE_PATH'),
+                            usernamePassword(credentialsId: 'dockerhub_creds', usernameVariable: 'U', passwordVariable: 'P')
+                        ]) {
+                            echo "Logging into Docker Hub as: ${U}"
+                            sh "echo ${P} | docker login -u ${U} --password-stdin"
+
+                            def fullImageName = "${U}/currency_app:${params.IMAGE_TAG}"
+
+                            echo "Starting green version: ${fullImageName} on port 8001"
+
+                            withEnv(["FULL_IMAGE=${fullImageName}", "S_PATH=${SECRET_FILE_PATH}"]) {
+                                sh 'IMAGE_NAME=${FULL_IMAGE} APP_PORT=8001 docker compose -p app-green --env-file ${S_PATH} up -d'
+                            }
                         }
                     }
                 }
@@ -32,7 +41,10 @@ pipeline {
         stage('Smoke tests') {
             steps {
                 script {
-                    echo "Testing Green on port 8001"
+                    echo "Waiting for Green slot to start..."
+                    sleep 5
+
+                    echo "Running tests against port 8001..."
                     sh '''
                         python3 -m venv venv
                         ./venv/bin/pip install -r requirements.txt
@@ -52,14 +64,21 @@ pipeline {
         stage('Switch Green to Blue') {
             steps {
                 script {
-                    echo "Tests passed! Switching Green to Blue"
-                    withCredentials([file(credentialsId: 'ENV_FILE', variable: 'SECRET_FILE_PATH')]) {
-                        sh "docker compose -p app-blue --env-file ${SECRET_FILE_PATH} down || true"
+                    echo "Tests passed! Moving Green version to Blue (Main Port 8000)"
 
-                        sh "IMAGE_NAME=${params.IMAGE_TAG} APP_PORT=8000 docker compose -p app-blue --env-file ${SECRET_FILE_PATH} up -d"
+                    withCredentials([
+                        file(credentialsId: 'ENV_FILE', variable: 'SECRET_FILE_PATH'),
+                        usernamePassword(credentialsId: 'dockerhub_creds', usernameVariable: 'U', passwordVariable: 'P')
+                    ]) {
+                        def fullImageName = "${U}/currency_app:${params.IMAGE_TAG}"
 
-                        sh "docker compose -p app-green down"
+                        withEnv(["FULL_IMAGE=${fullImageName}", "S_PATH=${SECRET_FILE_PATH}"]) {
+                            sh 'docker compose -p app-blue --env-file ${S_PATH} down || true'
+                            sh 'IMAGE_NAME=${FULL_IMAGE} APP_PORT=8000 docker compose -p app-blue --env-file ${S_PATH} up -d'
+                            sh 'docker compose -p app-green down'
+                        }
                     }
+                    echo "Switching complete. Service is live on port 8000."
                 }
             }
         }
@@ -67,7 +86,7 @@ pipeline {
 
     post {
         failure {
-            echo "Failure!!!"
+            echo "DEPLOYMENT FAILED! Cleaning up Green slot, Blue remains untouched."
             sh "docker compose -p app-green down || true"
         }
         always {
